services:

app:
  container_name: php-apache-app
  build:
  ports:
    - "8080:80"
  volumes:
    - ./html:/var/www/html  
  depends_on:
    - db_prod 
  networks:
    - inft2201_network

db_prod:
  image: postgres:16.1
  container_name: postgres_db
  environment:
    POSTGRES_DB: prod
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"
  volumes:
    - ./init-prod:/docker-entrypoint-initdb.d
  networks:
    - inft2201_network

networks:
  inft2201_network:
    driver: bridge    
    # name: inft2201_network